"""core schema

Revision ID: 2e2164a2b8cf
Revises: 0001_bootstrap
Create Date: 2026-07-24 22:36:18.317760+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e2164a2b8cf"
down_revision: str | Sequence[str] | None = "0001_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Every Postgres ENUM type this revision brings into existence. Kept as an
#: explicit list rather than reflected at runtime so a downgrade drops
#: exactly what this revision created and nothing a later one added. This
#: list was cross-checked against `pg_type` on a live database after a full
#: upgrade — 18 types, matching one-for-one.
_ENUM_TYPES: tuple[str, ...] = (
    "audit_action",
    "buyer_readiness",
    "channel_kind",
    "enrichment_kind",
    "enrichment_run_status",
    "lead_feedback_action",
    "lead_status",
    "listing_intent",
    "listing_status",
    "outbox_status",
    "owner_type",
    "persona",
    "property_type",
    "room_type",
    "signal_kind",
    "snapshot_source",
    "uad_condition",
    "user_role",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "realtor", "investor", "wholesaler", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user__email")),
        sa.UniqueConstraint("external_id", name=op.f("uq_app_user__external_id")),
    )
    op.create_index("ix_app_user__external_id", "app_user", ["external_id"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "user_login",
                "lead_viewed",
                "lead_contacted",
                "lead_feedback",
                "search_saved",
                "export",
                "admin_change",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_event__actor_action", "audit_event", ["actor_user_id", "action"], unique=False
    )
    op.create_index("ix_audit_event__occurred_at", "audit_event", ["occurred_at"], unique=False)
    op.create_table(
        "outbox_event",
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "dispatched", "failed", name="outbox_status"),
            nullable=False,
        ),
        sa.Column("dispatch_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
    )
    op.create_index(
        "ix_outbox_event__aggregate",
        "outbox_event",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_event__status_dispatch_after",
        "outbox_event",
        ["status", "dispatch_after"],
        unique=False,
    )
    op.create_table(
        "owner",
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=96), nullable=True),
        sa.Column("middle_name", sa.String(length=96), nullable=True),
        sa.Column("last_name", sa.String(length=96), nullable=True),
        sa.Column(
            "owner_type",
            sa.Enum(
                "individual",
                "trust",
                "llc",
                "corporation",
                "government",
                "unknown",
                name="owner_type",
            ),
            nullable=False,
        ),
        sa.Column("mailing_address", sa.String(length=512), nullable=True),
        sa.Column("enriched_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner")),
    )
    op.create_index("ix_owner__last_name", "owner", ["last_name"], unique=False)
    op.create_table(
        "property",
        sa.Column("address_hash", sa.String(length=64), nullable=False),
        sa.Column("street_number", sa.String(length=16), nullable=True),
        sa.Column("street_name", sa.String(length=128), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=96), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=False),
        sa.Column("county_fips", sa.String(length=5), nullable=True),
        sa.Column("apn", sa.String(length=64), nullable=True),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "property_type",
            sa.Enum(
                "single_family",
                "condo",
                "townhouse",
                "multi_family_2_4",
                "multi_family_5_plus",
                "manufactured",
                "land",
                "commercial",
                "other",
                name="property_type",
            ),
            nullable=False,
        ),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("lot_size_sqft", sa.Integer(), nullable=True),
        sa.Column("living_area_sqft", sa.Integer(), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("stories", sa.Integer(), nullable=True),
        sa.Column("garage_spaces", sa.Integer(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bedrooms IS NULL OR bedrooms >= 0", name=op.f("ck_property__bedrooms_nonneg")
        ),
        sa.CheckConstraint("length(state) = 2", name=op.f("ck_property__state_two_chars")),
        sa.CheckConstraint(
            "living_area_sqft IS NULL OR living_area_sqft >= 0",
            name=op.f("ck_property__living_area_nonneg"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property")),
        sa.UniqueConstraint("address_hash", name=op.f("uq_property__address_hash")),
        sa.UniqueConstraint("apn", "county_fips", name="uq_property__apn_county"),
    )
    op.create_index("ix_property__city_state", "property", ["city", "state"], unique=False)
    op.create_index(
        "ix_property__location", "property", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index("ix_property__postal_code", "property", ["postal_code"], unique=False)
    op.create_table(
        "buyer_profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_e164", sa.String(length=32), nullable=True),
        sa.Column("target_cities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_postal_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_price_cents", sa.Integer(), nullable=True),
        sa.Column("min_price_cents", sa.Integer(), nullable=True),
        sa.Column("min_bedrooms", sa.Integer(), nullable=True),
        sa.Column("min_bathrooms", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("min_living_area_sqft", sa.Integer(), nullable=True),
        sa.Column("max_living_area_sqft", sa.Integer(), nullable=True),
        sa.Column("property_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("must_haves", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nice_to_haves", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deal_breakers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "readiness",
            sa.Enum(
                "pre_qualified",
                "pre_approved",
                "cash",
                "just_looking",
                "unknown",
                name="buyer_readiness",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_buyer_profile__user_id__app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyer_profile")),
    )
    op.create_index(
        "ix_buyer_profile__user_active", "buyer_profile", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "contact_channel",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "phone_mobile",
                "phone_landline",
                "phone_voip",
                "email",
                "mailing_address",
                name="channel_kind",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.Column("rpc_probability", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("is_dnc", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
            name=op.f("fk_contact_channel__owner_id__owner"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_channel")),
    )
    op.create_index(
        "ix_contact_channel__value_hash", "contact_channel", ["value_hash"], unique=False
    )
    op.create_index(
        "uq_contact_channel__owner_kind_value_hash",
        "contact_channel",
        ["owner_id", "kind", "value_hash"],
        unique=True,
    )
    op.create_table(
        "deal_analysis",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("overall_condition", sa.String(length=16), nullable=True),
        sa.Column("condition_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("rehab_low_cents", sa.Integer(), nullable=True),
        sa.Column("rehab_high_cents", sa.Integer(), nullable=True),
        sa.Column("rehab_line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("avm_value_cents", sa.Integer(), nullable=True),
        sa.Column("avm_low_cents", sa.Integer(), nullable=True),
        sa.Column("avm_high_cents", sa.Integer(), nullable=True),
        sa.Column("avm_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("avm_provider", sa.String(length=64), nullable=True),
        sa.Column("arv_cents", sa.Integer(), nullable=True),
        sa.Column("arv_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("monthly_rent_cents", sa.Integer(), nullable=True),
        sa.Column("comps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comps_narrative", sa.Text(), nullable=True),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("quality_gate_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_deal_analysis__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_analysis")),
    )
    op.create_index(
        "ix_deal_analysis__property_version",
        "deal_analysis",
        ["property_id", "analysis_version"],
        unique=False,
    )
    op.create_table(
        "enrichment_run",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "photo_grading",
                "avm_valuation",
                "comps",
                "skip_trace",
                "signals",
                "deal_analysis",
                "comp_reranking",
                name="enrichment_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "skipped_budget",
                "skipped_provider_missing",
                name="enrichment_run_status",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd_micros", sa.Integer(), nullable=True),
        sa.Column("input_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_enrichment_run__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrichment_run")),
    )
    op.create_index(
        "ix_enrichment_run__property_kind_started",
        "enrichment_run",
        ["property_id", "kind", "started_at"],
        unique=False,
    )
    op.create_index(
        "uq_enrichment_run__idempotency_key", "enrichment_run", ["idempotency_key"], unique=True
    )
    op.create_table(
        "listing",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "mls_reso",
                "zillow",
                "redfin",
                "realtor_com",
                "propertyradar",
                "attom",
                "county_recorder",
                "county_assessor",
                "fsbo_portal",
                "manual",
                name="snapshot_source",
            ),
            nullable=False,
        ),
        sa.Column("source_listing_id", sa.String(length=128), nullable=False),
        sa.Column("mls_number", sa.String(length=64), nullable=True),
        sa.Column(
            "intent",
            sa.Enum("for_sale", "for_rent", "auction", "fsbo", name="listing_intent"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending",
                "contingent",
                "coming_soon",
                "sold",
                "withdrawn",
                "expired",
                "canceled",
                "unknown",
                name="listing_status",
            ),
            nullable=False,
        ),
        sa.Column("list_price_cents", sa.Integer(), nullable=True),
        sa.Column("original_list_price_cents", sa.Integer(), nullable=True),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("close_price_cents", sa.Integer(), nullable=True),
        sa.Column("listing_agent_name", sa.String(length=255), nullable=True),
        sa.Column("listing_agent_phone", sa.String(length=32), nullable=True),
        sa.Column("listing_agent_email", sa.String(length=255), nullable=True),
        sa.Column("listing_office_name", sa.String(length=255), nullable=True),
        sa.Column("remarks_public", sa.Text(), nullable=True),
        sa.Column("remarks_private", sa.Text(), nullable=True),
        sa.Column("photos_url_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_listing__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing")),
    )
    op.create_index("ix_listing__list_date", "listing", ["list_date"], unique=False)
    op.create_index(
        "ix_listing__property_status", "listing", ["property_id", "status"], unique=False
    )
    op.create_index(
        "uq_listing__source_source_listing_id",
        "listing",
        ["source", "source_listing_id"],
        unique=True,
    )
    op.create_table(
        "photo",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("url_sha256", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=32), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(length=1024), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_photo__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo")),
        sa.UniqueConstraint("property_id", "url_sha256", name="uq_photo__property_id__url_sha256"),
    )
    op.create_index(
        "ix_photo__property_order", "photo", ["property_id", "order_index"], unique=False
    )
    op.create_index(op.f("ix_photo_perceptual_hash"), "photo", ["perceptual_hash"], unique=False)
    op.create_table(
        "property_ownership",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("ownership_percent", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("acquired_date", sa.Date(), nullable=True),
        sa.Column("sold_date", sa.Date(), nullable=True),
        sa.Column("acquisition_price_cents", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
            name=op.f("fk_property_ownership__owner_id__owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_property_ownership__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_ownership")),
    )
    op.create_index(
        "ix_property_ownership__owner", "property_ownership", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_property_ownership__property_acquired",
        "property_ownership",
        ["property_id", "acquired_date"],
        unique=False,
    )
    op.create_table(
        "property_snapshot",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "mls_reso",
                "zillow",
                "redfin",
                "realtor_com",
                "propertyradar",
                "attom",
                "county_recorder",
                "county_assessor",
                "fsbo_portal",
                "manual",
                name="snapshot_source",
            ),
            nullable=False,
        ),
        sa.Column("source_record_id", sa.String(length=128), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("list_price_cents", sa.Integer(), nullable=True),
        sa.Column("last_sold_price_cents", sa.Integer(), nullable=True),
        sa.Column("last_sold_date", sa.Date(), nullable=True),
        sa.Column("days_on_market", sa.Integer(), nullable=True),
        sa.Column("price_per_sqft_cents", sa.Integer(), nullable=True),
        sa.Column("tax_assessed_value_cents", sa.Integer(), nullable=True),
        sa.Column("tax_annual_cents", sa.Integer(), nullable=True),
        sa.Column("hoa_monthly_cents", sa.Integer(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_property_snapshot__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_snapshot")),
        sa.UniqueConstraint(
            "property_id",
            "source",
            "source_record_id",
            "observed_at",
            name="uq_property_snapshot__source_record_observed",
        ),
    )
    op.create_index(
        "ix_property_snapshot__property_observed",
        "property_snapshot",
        ["property_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_property_snapshot__source_record",
        "property_snapshot",
        ["source", "source_record_id"],
        unique=False,
    )
    op.create_table(
        "saved_search",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "persona",
            sa.Enum("flipper", "wholesaler", "buyers_agent", "listing_agent", name="persona"),
            nullable=False,
        ),
        sa.Column("postal_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("regions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("min_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_saved_search__user_id__app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_search")),
    )
    op.create_index(
        "ix_saved_search__user_persona_active",
        "saved_search",
        ["user_id", "persona", "is_active"],
        unique=False,
    )
    op.create_table(
        "signal",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "nod_filed",
                "lis_pendens",
                "tax_delinquent",
                "code_violation",
                "vacancy_usps",
                "absentee_owner",
                "high_equity",
                "inherited_probate",
                "divorce_filed",
                "bankruptcy",
                "long_term_ownership",
                "recent_price_cut",
                "aged_listing",
                "withdrawn_recently",
                "expired_listing",
                "other",
                name="signal_kind",
            ),
            nullable=False,
        ),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("strength", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_signal__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal")),
    )
    op.create_index("ix_signal__kind_observed", "signal", ["kind", "observed_on"], unique=False)
    op.create_index(
        "ix_signal__property_kind_observed",
        "signal",
        ["property_id", "kind", "observed_on"],
        unique=False,
    )
    op.create_table(
        "photo_analysis",
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "room_type",
            sa.Enum(
                "exterior",
                "kitchen",
                "bathroom",
                "bedroom",
                "living_room",
                "dining_room",
                "basement",
                "garage",
                "utility",
                "yard",
                "aerial",
                "floor_plan",
                "other",
                name="room_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "condition",
            sa.Enum("C1", "C2", "C3", "C4", "C5", "C6", "NOT_VISIBLE", name="uad_condition"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observations", sa.String(length=2048), nullable=True),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd_micros", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
            name=op.f("fk_photo_analysis__photo_id__photo"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_analysis")),
    )
    op.create_index(
        "ix_photo_analysis__photo_analyzed",
        "photo_analysis",
        ["photo_id", "analyzed_at"],
        unique=False,
    )
    op.create_table(
        "score",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("deal_analysis_id", sa.UUID(), nullable=True),
        sa.Column(
            "persona",
            sa.Enum("flipper", "wholesaler", "buyers_agent", "listing_agent", name="persona"),
            nullable=False,
        ),
        sa.Column("scorer_version", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deal_analysis_id"],
            ["deal_analysis.id"],
            name=op.f("fk_score__deal_analysis_id__deal_analysis"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_score__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score")),
    )
    op.create_index("ix_score__persona_score", "score", ["persona", "score"], unique=False)
    op.create_index(
        "uq_score__property_persona_version",
        "score",
        ["property_id", "persona", "scorer_version"],
        unique=True,
    )
    op.create_table(
        "lead",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "persona",
            sa.Enum("flipper", "wholesaler", "buyers_agent", "listing_agent", name="persona"),
            nullable=False,
        ),
        sa.Column("score_id", sa.UUID(), nullable=True),
        sa.Column("score_snapshot", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "viewed",
                "contacted",
                "under_contract",
                "closed_won",
                "closed_lost",
                "dismissed",
                name="lead_status",
            ),
            nullable=False,
        ),
        sa.Column("surfaced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("saved_search_id", sa.UUID(), nullable=True),
        sa.Column("rank_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_lead__property_id__property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["saved_search_id"],
            ["saved_search.id"],
            name=op.f("fk_lead__saved_search_id__saved_search"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["score_id"], ["score.id"], name=op.f("fk_lead__score_id__score"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_lead__user_id__app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead")),
    )
    op.create_index("ix_lead__user_score_desc", "lead", ["user_id", "score_snapshot"], unique=False)
    op.create_index(
        "ix_lead__user_status_surfaced", "lead", ["user_id", "status", "surfaced_at"], unique=False
    )
    op.create_index(
        "uq_lead__property_user_persona", "lead", ["property_id", "user_id", "persona"], unique=True
    )
    op.create_table(
        "lead_feedback",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "accepted",
                "edited",
                "dismissed",
                "reported_inaccurate",
                name="lead_feedback_action",
            ),
            nullable=False,
        ),
        sa.Column("edits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.id"],
            name=op.f("fk_lead_feedback__lead_id__lead"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_lead_feedback__user_id__app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_feedback")),
    )
    op.create_index("ix_lead_feedback__lead", "lead_feedback", ["lead_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lead_feedback__lead", table_name="lead_feedback")
    op.drop_table("lead_feedback")
    op.drop_index("uq_lead__property_user_persona", table_name="lead")
    op.drop_index("ix_lead__user_status_surfaced", table_name="lead")
    op.drop_index("ix_lead__user_score_desc", table_name="lead")
    op.drop_table("lead")
    op.drop_index("uq_score__property_persona_version", table_name="score")
    op.drop_index("ix_score__persona_score", table_name="score")
    op.drop_table("score")
    op.drop_index("ix_photo_analysis__photo_analyzed", table_name="photo_analysis")
    op.drop_table("photo_analysis")
    op.drop_index("ix_signal__property_kind_observed", table_name="signal")
    op.drop_index("ix_signal__kind_observed", table_name="signal")
    op.drop_table("signal")
    op.drop_index("ix_saved_search__user_persona_active", table_name="saved_search")
    op.drop_table("saved_search")
    op.drop_index("ix_property_snapshot__source_record", table_name="property_snapshot")
    op.drop_index("ix_property_snapshot__property_observed", table_name="property_snapshot")
    op.drop_table("property_snapshot")
    op.drop_index("ix_property_ownership__property_acquired", table_name="property_ownership")
    op.drop_index("ix_property_ownership__owner", table_name="property_ownership")
    op.drop_table("property_ownership")
    op.drop_index(op.f("ix_photo_perceptual_hash"), table_name="photo")
    op.drop_index("ix_photo__property_order", table_name="photo")
    op.drop_table("photo")
    op.drop_index("uq_listing__source_source_listing_id", table_name="listing")
    op.drop_index("ix_listing__property_status", table_name="listing")
    op.drop_index("ix_listing__list_date", table_name="listing")
    op.drop_table("listing")
    op.drop_index("uq_enrichment_run__idempotency_key", table_name="enrichment_run")
    op.drop_index("ix_enrichment_run__property_kind_started", table_name="enrichment_run")
    op.drop_table("enrichment_run")
    op.drop_index("ix_deal_analysis__property_version", table_name="deal_analysis")
    op.drop_table("deal_analysis")
    op.drop_index("uq_contact_channel__owner_kind_value_hash", table_name="contact_channel")
    op.drop_index("ix_contact_channel__value_hash", table_name="contact_channel")
    op.drop_table("contact_channel")
    op.drop_index("ix_buyer_profile__user_active", table_name="buyer_profile")
    op.drop_table("buyer_profile")
    op.drop_index("ix_property__postal_code", table_name="property")
    op.drop_index("ix_property__location", table_name="property", postgresql_using="gist")
    op.drop_index("ix_property__city_state", table_name="property")
    op.drop_table("property")
    op.drop_index("ix_owner__last_name", table_name="owner")
    op.drop_table("owner")
    op.drop_index("ix_outbox_event__status_dispatch_after", table_name="outbox_event")
    op.drop_index("ix_outbox_event__aggregate", table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index("ix_audit_event__occurred_at", table_name="audit_event")
    op.drop_index("ix_audit_event__actor_action", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index("ix_app_user__external_id", table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###

    # Hand-added: autogenerate emits CREATE TYPE implicitly (as a side effect
    # of the first column that references each enum) but never emits the
    # matching DROP TYPE. Without this block a downgrade leaves 18 orphaned
    # types behind and the very next `upgrade` dies with
    # `type "user_role" already exists`. Verified by round-tripping
    # upgrade -> downgrade -> upgrade against a live Postgres.
    for enum_name in _ENUM_TYPES:
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
